version: '3.4'

services:
  evently.api:
    image: evently.api
    container_name: evently.api
    build:
      context: .
      dockerfile: Evently.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
